### Step 2: Feature Engineering

In [13]:
import pandas as pd
import numpy as np

In [14]:
df=pd.read_csv('cleaned_data.csv')
df.head()

,name,maincity,city,rating,rating_count,cost,cuisine
0,AB FOODS POINT,Abohar,Abohar,4.0,0,200,"Beverages,Pizzas"
1,Janta Sweet House,Abohar,Abohar,4.4,50,200,"Sweets,Bakery"
2,theka coffee desi,Abohar,Abohar,3.8,100,100,Beverages
3,Singh Hut,Abohar,Abohar,3.7,20,250,"Fast Food,Indian"
4,GRILL MASTERS,Abohar,Abohar,4.0,0,250,"Italian-American,Fast Food"

####  2.1 Split Cuisine

In [15]:
df['cuisine'] = df['cuisine'].str.split(',')

In [16]:
df.head()

,name,maincity,city,rating,rating_count,cost,cuisine
0,AB FOODS POINT,Abohar,Abohar,4.0,0,200,"[Beverages, Pizzas]"
1,Janta Sweet House,Abohar,Abohar,4.4,50,200,"[Sweets, Bakery]"
2,theka coffee desi,Abohar,Abohar,3.8,100,100,[Beverages]
3,Singh Hut,Abohar,Abohar,3.7,20,250,"[Fast Food, Indian]"
4,GRILL MASTERS,Abohar,Abohar,4.0,0,250,"[Italian-American, Fast Food]"

#### 2.2 Encode Cuisine

In [17]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
cuisine_encoded = mlb.fit_transform(df['cuisine'])
cuisine_df = pd.DataFrame(cuisine_encoded, columns=mlb.classes_)

#### 2.3 Encode City

In [18]:
city_encoded = pd.get_dummies(df['city'], prefix='city')
maincity_encoded = pd.get_dummies(df['maincity'], prefix='maincity')

#### 2.4 Combine Features

In [19]:
final_df = pd.concat([df[['cost', 'rating']],   # numeric features
    city_encoded,
    cuisine_df
], axis=1)

####  2.5 Scale Features

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
final_df[['cost', 'rating']] = scaler.fit_transform(final_df[['cost', 'rating']])

#### 2.6 Final Check

In [21]:
print(final_df.isnull().sum().sum())   # should be 0
print(final_df.dtypes)                 # all numeric

0
cost                            float64
rating                          float64
city_Abids & Koti                  bool
city_Abohar                        bool
city_Adajan                        bool
                                 ...
Use Code JUMBO30 to avail         int64
Use code XPRESS121 to avail.      int64
Vietnamese                        int64
Waffle                            int64
indian                            int64
Length: 949, dtype: object

#### 2.7 Save Encoded Data

In [22]:
final_df.to_csv('encoded_data.csv', index=False)